import { Player, MatchRecord, ClubStats } from './types';

export const clubStatsData: ClubStats = {
  skillRating: 1831,
  div: 4,
  bestDiv: 3,
  rank: "#100+",
  totalPlayed: 533,
  winRate: "46.0%",
  seasonRecord: "6W - 1D - 3L",
  goalDifference: "+5 (45 - 40)",
  statusStreak: "6 WINS IN LAST 10 🔥",
  wins: 245,
  draws: 65,
  losses: 223,
  goals: 1872
};

export const playersData: Player[] = [
  {
    name: "ALMOUSA3M",
    pro: "Almousa3m",
    img: "almousa3m.png",
    ovr: 90,
    pos: "ST",
    h: "190 CM",
    gen: { games: 395, winP: 51, rat: 8.1, motm: 76 },
    atk: { goals: 437, gpm: 1.11, shotS: 38, ast: 428 },
    team: { passes: 6531, passS: 78 },
    def: { red: 6, tack: 264, gk: 1 },
    ai: {
      carry: 88,
      cL: "Backpack 🎒",
      pwr: 94,
      clu: 68,
      pad: "Legit ✅",
      bpts: 1040,
      tip: "Elite scorer & playmaker. Dominant in air, finishing, and clutch moments."
    }
  },
  {
    name: "H2SSAIN_28",
    pro: "bombar",
    img: "h2ssain28.png",
    ovr: 88,
    pos: "ST",
    h: "186 CM",
    gen: { games: 450, winP: 45, rat: 7.5, motm: 38 },
    atk: { goals: 442, gpm: 0.98, shotS: 29, ast: 334 },
    team: { passes: 4869, passS: 74 },
    def: { red: 14, tack: 173, gk: 0 },
    ai: {
      carry: 68,
      cL: "Key Player 💪",
      pwr: 90,
      clu: 74,
      pad: "Padder 📊",
      bpts: 920,
      tip: "Prolific striker. Top goalscorer with high impact in tight games."
    }
  },
  {
    name: "M-_-_-_-11_11",
    pro: "PEDRI",
    img: "m1111.png",
    ovr: 89,
    pos: "CM",
    h: "175 CM",
    gen: { games: 466, winP: 46, rat: 8.1, motm: 75 },
    atk: { goals: 244, gpm: 0.52, shotS: 32, ast: 297 },
    team: { passes: 7084, passS: 76 },
    def: { red: 16, tack: 472, gk: 0 },
    ai: {
      carry: 78,
      cL: "Backpack 🎒",
      pwr: 82,
      clu: 60,
      pad: "Legit ✅",
      bpts: 960,
      tip: "Midfield engine. Controls tempo with 7,000+ passes and 470+ tackles."
    }
  },
  {
    name: "h7modi_77",
    pro: "M. Almarhoon",
    img: "logo.png",
    ovr: 80,
    pos: "LW",
    h: "162 CM",
    gen: { games: 237, winP: 47, rat: 8.0, motm: 36 },
    atk: { goals: 116, gpm: 0.49, shotS: 37, ast: 165 },
    team: { passes: 3673, passS: 75 },
    def: { red: 32, tack: 398, gk: 0 },
    ai: {
      carry: 71,
      cL: "Backpack 🎒",
      pwr: 76,
      clu: 54,
      pad: "Suspicious 🤔",
      bpts: 850,
      tip: "Consistent winger & relentless presser. High dribbling efficiency."
    }
  },
  {
    name: "Basabeso2",
    pro: "Basabeso",
    img: "basabeso2.png",
    ovr: 90,
    pos: "CB",
    h: "185 CM",
    gen: { games: 375, winP: 49, rat: 7.2, motm: 23 },
    atk: { goals: 198, gpm: 0.53, shotS: 39, ast: 117 },
    team: { passes: 4065, passS: 85 },
    def: { red: 20, tack: 341, gk: 0 },
    ai: {
      carry: 50,
      cL: "Contributor 👍",
      pwr: 42,
      clu: 35,
      pad: "Padder 📊",
      bpts: 740,
      tip: "Defensive wall. Elite pass accuracy from back (85% precision)."
    }
  },
  {
    name: "H7MODI_07",
    pro: "M. Almarhoon",
    img: "h7modi07.png",
    ovr: 82,
    pos: "CAM",
    h: "162 CM",
    gen: { games: 170, winP: 48, rat: 7.4, motm: 14 },
    atk: { goals: 79, gpm: 0.46, shotS: 33, ast: 92 },
    team: { passes: 2146, passS: 74 },
    def: { red: 23, tack: 243, gk: 0 },
    ai: {
      carry: 52,
      cL: "Contributor 👍",
      pwr: 85,
      clu: 70,
      pad: "Suspicious 📊",
      bpts: 790,
      tip: "Rising playmaker. High recent form and creative play in attacking midfield."
    }
  },
  {
    name: "yo0ousef25",
    pro: "H. Huss29",
    img: "yo0ousef25.png",
    ovr: 88,
    pos: "RW",
    h: "175 CM",
    gen: { games: 355, winP: 45, rat: 7.1, motm: 11 },
    atk: { goals: 237, gpm: 0.67, shotS: 48, ast: 98 },
    team: { passes: 3803, passS: 76 },
    def: { red: 16, tack: 183, gk: 0 },
    ai: {
      carry: 44,
      cL: "Contributor 👍",
      pwr: 72,
      clu: 49,
      pad: "High Padder 📊",
      bpts: 710,
      tip: "Clinical finisher. High conversion rate (48%) and deadly from wing positions."
    }
  }
];

export const matchesData: MatchRecord[] = [
  { res: "L", score: "4-11", opp: "lvc11", scorers: "yo0ousef25 (2), H2SSAIN_28, H7modi_07", motm: "almousa3m" },
  { res: "W", score: "5-2", opp: "The Walkir", scorers: "almousa3m, yo0ousef25, H2SSAIN_28 (2), H7modi_07", motm: "H2SSAIN_28" },
  { res: "L", score: "1-4", opp: "SAX7X7", scorers: "almousa3m", motm: "almousa3m" },
  { res: "W", score: "8-4", opp: "friends4", scorers: "yo0ousef25 (2), Basabeso2, H2SSAIN_28 (2), H7modi_07 (3)", motm: "H2SSAIN_28" },
  { res: "W", score: "3-0", opp: "G L 0  R Y", scorers: "yo0ousef25 (3)", motm: "yo0ousef25" },
  { res: "W", score: "6-1", opp: "Kallay Lullay", scorers: "almousa3m, yo0ousef25 (3), H2SSAIN_28, H7modi_07", motm: "H7modi_07" },
  { res: "W", score: "6-4", opp: "AL Hayaniya", scorers: "almousa3m, yo0ousef25 (2), Basabeso2, H2SSAIN_28, H7modi_07", motm: "H7modi_07" },
  { res: "D", score: "6-6", opp: "teststeron", scorers: "almousa3m, H2SSAIN_28 (3), H7modi_07 (2)", motm: "almousa3m" },
  { res: "W", score: "4-3", opp: "Rushn", scorers: "yo0ousef25, Basabeso2, H2SSAIN_28, H7modi_07", motm: "Basabeso2" },
  { res: "L", score: "2-5", opp: "8rdhab", scorers: "yo0ousef25", motm: "yo0ousef25" }
];

export const i18n = {
  ar: {
    sr_title: "التقييم المهاري للنادي",
    div: "القسم",
    best: "الأفضل",
    rank: "العالمي",
    total_m: "إجمالي المباريات",
    win_rate: "نسبة الفوز",
    season_title: "متتبع الموسم (30 يوم)",
    record: "السجل",
    gd: "فارق الأهداف",
    streak: "الحالة",
    lifetime: "إحصائيات الدوري الكلية",
    wins: "فوز",
    draws: "تعادل",
    losses: "خسارة",
    goals: "أهداف",
    squad_title: "قائمة الفريق الأول",
    pwr_rank: "ترتيب القوة الأسبوعي",
    carry: "تصنيف من يحمل الفريق",
    padder: "كاشف تضخيم الأرقام",
    clu_title: "مؤشر الحسم",
    ballon_main: "الكرة الذهبية 2026",
    ballon_full: "الترتيب الكامل",
    matches_history: "سجل المواجهات الأخيرة",
    nav_home: "الرئيسية",
    nav_squad: "الفريق",
    nav_ai: "الذكاء",
    nav_ballon: "البالون",
    nav_matches: "المباريات",
    close: "إغلاق",
    gen_t: "إحصائيات عامة",
    atk_t: "الهجوم",
    team_t: "اللعب الجماعي",
    def_t: "الدفاع",
    games: "مباريات",
    rating: "التقييم",
    motm: "رجل المباراة",
    goals_stat: "الأهداف",
    assists: "الصناعة",
    gpm: "معدل التهديف",
    red_cards: "الكروت الحمراء",
    tackles: "التدخلات",
    clean_sheets: "شباك نظيفة (حارس)",
    gold: "ذهب",
    silver: "فضة",
    bronze: "برونز",
    pts: "نقطة",
    pwr: "قوة"
  },
  en: {
    sr_title: "CLUB SKILL RATING",
    div: "DIV",
    best: "BEST",
    rank: "RANK",
    total_m: "TOTAL MATCHES",
    win_rate: "WIN RATE",
    season_title: "SEASON TRACKER (30D)",
    record: "Record",
    gd: "Goal Diff",
    streak: "Status",
    lifetime: "LIFETIME LEAGUE STATS",
    wins: "Wins",
    draws: "Draws",
    losses: "Losses",
    goals: "Goals",
    squad_title: "FIRST TEAM SQUAD",
    pwr_rank: "POWER RANKINGS",
    carry: "CARRY RANKINGS",
    padder: "STAT PADDER DETECTOR",
    clu_title: "CLUTCH INDEX",
    ballon_main: "BALLON D'OR 2026",
    ballon_full: "FULL RANKING",
    matches_history: "MATCH HISTORY",
    nav_home: "HOME",
    nav_squad: "SQUAD",
    nav_ai: "AI HUB",
    nav_ballon: "BALLON",
    nav_matches: "MATCHES",
    close: "CLOSE",
    gen_t: "GENERAL",
    atk_t: "ATTACKING",
    team_t: "TEAMPLAY",
    def_t: "DEFENDING",
    games: "Games",
    rating: "Rating",
    motm: "MOTM",
    goals_stat: "Goals",
    assists: "Assists",
    gpm: "GPM",
    red_cards: "Red Cards",
    tackles: "Tackles",
    clean_sheets: "GK Clean Sheets",
    gold: "GOLD",
    silver: "SILVER",
    bronze: "BRONZE",
    pts: "PTS",
    pwr: "PWR"
  }
};
