/**
 * TAWHID FC — البيانات القابلة للتعديل (2027 فقط)
 * احفظ تعديل هذا الملف ثم حدّث صفحة index.html، وستظهر التغييرات للجميع عند رفع الملفين للاستضافة.
 * مهم: لا توجد لوحة حفظ داخل المتصفح، فمصدر الحقيقة الوحيد هو هذا الملف.
 * ضع index.html و data.js والصور في المجلد نفسه.
 * اكتب الأرقام بدون علامات اقتباس، واستخدم null للإحصائية التي لا تملك قيمتها.
 * ترتيب اللاعبين وتقييمهم يُحسب تلقائيًا في index.html حسب المركز.
 * يمكنك إضافة خبر: { title:"عنوان", date:"2027/01/01", image:"A2.PNG", text:"النص" }
 * يمكنك إضافة صورة: { title:"العنوان", image:"B2.PNG" }
 * يمكنك إضافة مباراة: { date:"2027-01-01 21:00", opponent:"الفريق المنافس", score:"3-1", result:"W", scorers:"الاسم (2)", motm:"الاسم" }
 * رموز النتائج: W فوز، D تعادل، L خسارة.
 * المباريات: اترك قيم الفريق الأساسية null إذا أردت استنتاجها آليًا من سجل المباريات.
 * لا تضع الفاصلة , بعد آخر عنصر في القائمة إن كنت غير متأكد من الصياغة.
 */
window.TAWHID_DATA = {
  "description": "نحو موسم جديد... معًا نكتب التاريخ.",
  "team": {
    "games": null,
    "wins": null,
    "draws": null,
    "losses": null,
    "goals": null,
    "conceded": null,
    "skill": null,
    "division": null,
    "bestDivision": null,
    "promotions": null,
    "relegations": null,
    "playoffs": null,
    "leagueGames": null,
    "platform": "GEN5"
  },
  "players": [
    {
      "id": "alm",
      "name": "Almousa3m",
      "nationality": "السعودية",
      "pos": "ST",
      "photo": "Alm27.PNG",
      "games": null,
      "goals": null,
      "assists": null,
      "motm": null,
      "passes": null,
      "passPct": null,
      "shots": null,
      "shotPct": null,
      "tackles": null,
      "tacklePct": null,
      "interceptions": null,
      "clearances": null,
      "blocks": null,
      "saves": null,
      "savePct": null,
      "csDef": null,
      "csGK": null,
      "red": null,
      "yellow": null,
      "win": null,
      "rating": null,
      "minutes": null,
      "points": null
    },
    {
      "id": "basa",
      "name": "Basabeso2",
      "nationality": "السعودية",
      "pos": "LW",
      "photo": "Basa27.PNG",
      "games": null,
      "goals": null,
      "assists": null,
      "motm": null,
      "passes": null,
      "passPct": null,
      "shots": null,
      "shotPct": null,
      "tackles": null,
      "tacklePct": null,
      "interceptions": null,
      "clearances": null,
      "blocks": null,
      "saves": null,
      "savePct": null,
      "csDef": null,
      "csGK": null,
      "red": null,
      "yellow": null,
      "win": null,
      "rating": null,
      "minutes": null,
      "points": null
    },
    {
      "id": "hss",
      "name": "H2ssain_28",
      "nationality": "السعودية",
      "pos": "ST",
      "photo": "Hss27.PNG",
      "games": null,
      "goals": null,
      "assists": null,
      "motm": null,
      "passes": null,
      "passPct": null,
      "shots": null,
      "shotPct": null,
      "tackles": null,
      "tacklePct": null,
      "interceptions": null,
      "clearances": null,
      "blocks": null,
      "saves": null,
      "savePct": null,
      "csDef": null,
      "csGK": null,
      "red": null,
      "yellow": null,
      "win": null,
      "rating": null,
      "minutes": null,
      "points": null
    },
    {
      "id": "m",
      "name": "M-*-*-_-11_11",
      "nationality": "السعودية",
      "pos": "CM",
      "photo": "M--27.PNG",
      "games": null,
      "goals": null,
      "assists": null,
      "motm": null,
      "passes": null,
      "passPct": null,
      "shots": null,
      "shotPct": null,
      "tackles": null,
      "tacklePct": null,
      "interceptions": null,
      "clearances": null,
      "blocks": null,
      "saves": null,
      "savePct": null,
      "csDef": null,
      "csGK": null,
      "red": null,
      "yellow": null,
      "win": null,
      "rating": null,
      "minutes": null,
      "points": null
    },
    {
      "id": "h77",
      "name": "H7modi_77",
      "nationality": "السعودية",
      "pos": "CM",
      "photo": "H7modi7727.PNG",
      "games": null,
      "goals": null,
      "assists": null,
      "motm": null,
      "passes": null,
      "passPct": null,
      "shots": null,
      "shotPct": null,
      "tackles": null,
      "tacklePct": null,
      "interceptions": null,
      "clearances": null,
      "blocks": null,
      "saves": null,
      "savePct": null,
      "csDef": null,
      "csGK": null,
      "red": null,
      "yellow": null,
      "win": null,
      "rating": null,
      "minutes": null,
      "points": null
    },
    {
      "id": "h07",
      "name": "H7modi_07",
      "nationality": "مصر",
      "pos": "ST",
      "photo": "H7modi0727.PNG",
      "games": null,
      "goals": null,
      "assists": null,
      "motm": null,
      "passes": null,
      "passPct": null,
      "shots": null,
      "shotPct": null,
      "tackles": null,
      "tacklePct": null,
      "interceptions": null,
      "clearances": null,
      "blocks": null,
      "saves": null,
      "savePct": null,
      "csDef": null,
      "csGK": null,
      "red": null,
      "yellow": null,
      "win": null,
      "rating": null,
      "minutes": null,
      "points": null
    },
    {
      "id": "yo",
      "name": "Yo0ousef_25",
      "nationality": "جنوب أفريقيا",
      "pos": "RW",
      "photo": "Yo27.PNG",
      "games": null,
      "goals": null,
      "assists": null,
      "motm": null,
      "passes": null,
      "passPct": null,
      "shots": null,
      "shotPct": null,
      "tackles": null,
      "tacklePct": null,
      "interceptions": null,
      "clearances": null,
      "blocks": null,
      "saves": null,
      "savePct": null,
      "csDef": null,
      "csGK": null,
      "red": null,
      "yellow": null,
      "win": null,
      "rating": null,
      "minutes": null,
      "points": null
    },
    {
      "id": "alaly",
      "name": "Alaly19",
      "nationality": "قطر",
      "pos": "ST",
      "photo": "Alaly27.PNG",
      "games": null,
      "goals": null,
      "assists": null,
      "motm": null,
      "passes": null,
      "passPct": null,
      "shots": null,
      "shotPct": null,
      "tackles": null,
      "tacklePct": null,
      "interceptions": null,
      "clearances": null,
      "blocks": null,
      "saves": null,
      "savePct": null,
      "csDef": null,
      "csGK": null,
      "red": null,
      "yellow": null,
      "win": null,
      "rating": null,
      "minutes": null,
      "points": null
    }
  ],

"news": [
  {
    "title": "نادي التوحيد يعلن انطلاق موسم 2027",
    "date": "2026/10/03",
    "image": "A1.PNG",
    "text": "يسر نادي التوحيد الإعلان عن انطلاق الموسم الجديد، وسط طموحات كبيرة لتحقيق الإنجازات."
  },
  {
    "title": "ترتيب جوائز الكرة الذهبية لعام 2026",
    "date": "2026/9/23",
    "image": "A2.PNG",
    "text": "حقق اللاعب Almousa3m الكرة الذهبية للمرة الثانية على التوالي"
  }
],
  "gallery": [],
  "matches": []
};
